config/routes.rb
PeriodicTable::Application.routes.draw do

   root 'home#index'

  resources :elements

  namespace :administration do
    resources :pictures
    resources :elements
  end

  get "administration" => "administration/elements#index"

  

end

app/models/element.rb
class Element < ActiveRecord::Base
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  
  attr_accessible :title, :caption, :resource_type, :resource_id, :resource, :image
  
  belongs_to :resource, :polymorphic => true, :counter_cache => true
  
  acts_as_list :scope => [:resource_id, :resource_type]
  
  Paperclip.interpolates :title_url do |attachment, style|
    attachment.instance.title_url
  end
  Paperclip.interpolates :style_upcase do |attachment, style|
    style_upcase = style.to_s.upcase
    return style_upcase
  end
  Paperclip.interpolates :directory_id do |attachment, style|
    id = (attachment.instance.id).to_s.rjust(8,"0")
    directory_id = id.scan(/..../)
    directory_id = directory_id.join('/')
    return directory_id
  end
  
  PAPERCLIP_PATH = ":rails_root/public/attachments/:class-:attachment/:directory_id/:style_upcase-:title_url.:extension"
  if Rails.env == "production"
    PAPERCLIP_URL =                  "/attachments/:class-:attachment/:directory_id/:style/:title_url.:extension"
  else
    PAPERCLIP_URL =                  "/attachments/:class-:attachment/:directory_id/:style_upcase-:title_url.:extension"
  end
  has_attached_file :image,
                    :styles => {
                      :gallery_large    => { :format => 'jpg', :quality => 100, :geometry => '670x500>' },
                      :large            => { :format => 'jpg', :quality => 100, :geometry => '640x640>' },
                      :featured_small   => { :format => 'jpg', :quality => 100, :geometry => '245x200#' },
                      :homepage_large   => { :format => 'jpg', :quality => 100, :geometry => '640x390#' },
                      :homepage_medium  => { :format => 'jpg', :quality => 100, :geometry => '300x300#' },
                      :homepage_small   => { :format => 'jpg', :quality => 100, :geometry => '300x150#' },
                      :thumbnail        => { :format => 'jpg', :quality => 100, :geometry => '160x130#' },
                      :innerpage_medium => { :format => 'jpg', :quality => 100, :geometry => '440x440>' },
                      :original         => {                   :quality => 100, :geometry => '', :animated => true }
                    },
                    :path => PAPERCLIP_PATH,
                    :url  => PAPERCLIP_URL

  validates :title, :presence => true
  
  before_validation :change_filenames, :strip_attributes

  def path(place = nil)
    case self.resource_type
    when "Article"
      return "/articles/#{self.resource_id}/photo/#{self.id}-#{Utility::friendly_url(self.title)}"
    when "PlaceInfo"
      return "/places/#{self.resource.place_id}-#{Utility::friendly_url(self.resource.place.name)}/information/photo/#{self.id}-#{Utility::friendly_url(self.title)}"
    when "Hotel"
      return "/places/#{self.resource.place_id}-#{Utility::friendly_url(self.resource.place.name)}/hotels/#{self.resource_id}/photo/#{self.id}-#{Utility::friendly_url(self.title)}"
    else  
      return "/places/#{self.resource.place.id}-#{Utility::friendly_url(self.resource.place.name)}/#{self.resource_type.downcase.pluralize}/#{self.resource_id}/photo/#{self.id}-#{Utility::friendly_url(self.title)}"
    end

  end

  def get_prev_and_next
    positions = "#{self.position - 1}, #{self.position + 1}"

    pictures = Picture.where("resource_id = #{self.resource_id} AND 
                             resource_type = '#{self.resource_type}' AND
                             position IN (#{positions})")
                      .order("position")
    if pictures.size == 2
      prev_picture = pictures[0]
      next_picture = pictures[1]
    elsif pictures.size == 1 and self.position == 1
      prev_picture = nil
      next_picture = pictures[0]
    else
      prev_picture = pictures[0]
      next_picture = nil
    end
    return {:prev => prev_picture, :next => next_picture}
  end

  private

  def strip_attributes
    # normalize attributes
    self.title.strip!
    self.title_url = Utility::friendly_url(self.title)
  end

  def change_filenames
    # if there is an update to the title, the file names should be changed accordingly
    if not self.new_record? and self.title_changed?
      self.image = self.image
    end
  end

end

app/controllers/administration/elements_controller.rb
class Administration::ElementsController < ApplicationController
end

app/controllers/administration_controller.rb
class AdministrationController < ApplicationController

	http_basic_authenticate_with :name => "Emilia", :password => "Uzunova"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_action :set_element, only: [:show, :edit, :update, :destroy]

  # GET /elements
  # GET /elements.json
  def index
    @elements = Element.all
  end

  # GET /elements/1
  # GET /elements/1.json
  def show
  end

  # GET /elements/new
  def new
    @element = Element.new
  end

  # GET /elements/1/edit
  def edit
  end

  # POST /elements
  # POST /elements.json
  def create
    @element = Element.new(element_params)

    respond_to do |format|
      if @element.save
        format.html { redirect_to @element, notice: 'Element was successfully created.' }
        format.json { render action: 'show', status: :created, location: @element }
      else
        format.html { render action: 'new' }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elements/1
  # PATCH/PUT /elements/1.json
  def update
    respond_to do |format|
      if @element.update(element_params)
        format.html { redirect_to @element, notice: 'Element was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elements/1
  # DELETE /elements/1.json
  def destroy
    @element.destroy
    respond_to do |format|
      format.html { redirect_to elements_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_element
      @element = Element.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def element_params
      params.require(:element).permit(:symbol, :number)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
		
	end
end

app/helpers/administration/elements_helper.rb
module Administration::ElementsHelper
end

app/helpers/administration_helper.rb
module AdministrationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/elements/_form.html.erb
<%= form_for(@element) do |f| %>
  <% if @element.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@element.errors.count, "error") %> prohibited this element from being saved:</h2>

      <ul>
      <% @element.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
  
  <div>
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  
  <div>
    <%= f.label :symbol %><br />
    <%= f.text_field :symbol %>
  </div>

  <div>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :name_lat %><br />
    <%= f.text_field :name_lat %>
  </div>

  <div>
    <%= f.label :group %><br />
    <%= select_tag(:group, options_for_select((1..8).to_a)) %>
  </div>

  <div>
    <%= f.label :boiling_point %><br />
    <%= f.text_field :boiling_point %>
  </div>

  <div>
    <%= f.label :meltig_point %><br />
    <%= f.text_field :melting_point %>
  </div>

  <div>
    <%= f.label :phase %><br />
    <%= f.text_field :phase %>
  </div>

  <div>
    <%= f.label :atomic_weight %><br />
    <%= f.text_field :atomic_weight %>
  </div>

  <div>
    <%= f.label :toxicity %><br />
    <%= check_box_tag(:toxicity) %>
  </div>

  <div>
    <%= f.label :summary %><br />
    <%= f.text_field(:summary) %>
  </div>

  <div>
    <%= f.label :content %><br />
    <%= f.text_area(:content) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/elements/edit.html.erb
<h1>Editing element</h1>

<%= render 'form' %>

<%= link_to 'Show', @element %> |
<%= link_to 'Back', elements_path %>

app/views/elements/index.html.erb
<h1>Listing elements</h1>

<table class="elements">
  <thead>
    <tr>
      <th>Номер</th>
      <th>Символ</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @elements.each do |element| %>
      <tr>
        <td>
          <%= element.number %>
        </td> 
        <td>
          <%= element.symbol %>
        </td> 
        <td>
          <%= link_to 'Show', element %>
          <%= link_to 'Edit', edit_element_path(element) %>
          <%#= link_to 'Destroy', element, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Element', new_element_path %>

app/views/elements/new.html.erb
<h1>New element</h1>

<%= render 'form' %>

<%= link_to 'Back', elements_path %>

app/views/elements/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_element_path(@element) %> |
<%= link_to 'Back', elements_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PeriodicTable</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		 <%= render :partial => "/shared/header" %>
	</header>
	<nav class="group">
		<%= render :partial => "/shared/navigation" %>	
	</nav>
	<div id="mainContent">
		<%= yield %>
	</div>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PeriodicTable</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		 <%= render :partial => "/shared/header" %>
	</header>
	<nav class="group">
		<%= render :partial => "/shared/navigation" %>	
	</nav>
		<%= yield %>
</body>
</html>

app/views/shared/_header.html.erb
<a href="/"><img src="/menu/logoq.png"/></a>

app/views/shared/_navigation.html.erb
<ul>
	<li class="home"><a href="#" title="">Home</a></li>
	<li><a href="#" title="">За мен</a></li>
	<li><a href="#" title="">Контакти</a></li>
	<li><a href="#" title="">Testimonials</a></li>
</ul>